<?php

return [
    
    'default' => "rounded",
    'xs' => "rounded-xs",
    'sm' => "rounded-sm",
    'md' => "rounded-md",
    'lg' => "rounded-lg",
    'xl' => "rounded-xl",
    '2xl' => "rounded-2xl",
    '3xl' => "rounded-3xl",
    '4xl' => "rounded-4xl",
    'none' => "rounded-none",
    'full' => "rounded-full",

    'top-default' => 'rounded-t',
    'top-xs' => 'rounded-t-xs',
    'top-sm' => 'rounded-t-sm',
    'top-md' => 'rounded-t-md',
    'top-lg' => 'rounded-t-lg',
    'top-xl' => 'rounded-t-xl',
    'top-2xl' => 'rounded-t-2xl',
    'top-3xl' => 'rounded-t-3xl',
    'top-4xl' => 'rounded-t-4xl',
    'top-none' => 'rounded-t-none',

    'bottom-default' => 'rounded-b',
    'bottom-xs' => 'rounded-b-xs', 
    'bottom-sm' => 'rounded-b-sm',
    'bottom-md' => 'rounded-b-md',
    'bottom-lg' => 'rounded-b-lg',
    'bottom-xl' => 'rounded-b-xl',
    'bottom-2xl' => 'rounded-b-2xl',
    'bottom-3xl' => 'rounded-b-3xl',
    'bottom-4xl' => 'rounded-b-4xl',
    'bottom-none' => 'rounded-b-none',

    'left-default' => 'rounded-l',
    'left-xs' => 'rounded-l-xs',
    'left-sm' => 'rounded-l-sm',
    'left-md' => 'rounded-l-md',
    'left-lg' => 'rounded-l-lg',
    'left-xl' => 'rounded-l-xl',
    'left-2xl' => 'rounded-l-2xl',
    'left-3xl' => 'rounded-l-3xl',
    'left-4xl' => 'rounded-l-4xl',
    'left-none' => 'rounded-l-none',

    'right-default' => 'rounded-r',
    'right-xs' => 'rounded-r-xs',
    'right-sm' => 'rounded-r-sm',
    'right-md' => 'rounded-r-md',
    'right-lg' => 'rounded-r-lg',
    'right-xl' => 'rounded-r-xl',
    'right-2xl' => 'rounded-r-2xl',
    'right-3xl' => 'rounded-r-3xl',
    'right-4xl' => 'rounded-r-4xl',
    'right-none' => 'rounded-r-none',

];